"""add catalog models

Revision ID: eee1d487fbcd
Revises: 202607030001
Create Date: 2026-07-03 18:55:01.187142
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'eee1d487fbcd'
down_revision: str | Sequence[str] | None = '202607030001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_profile_id', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('secret_ref', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_type in ('rclone', 'oauth', 'service_account', 'other')", name='ck_auth_profiles_auth_type'),
    sa.CheckConstraint("provider in ('google_drive', 'local', 's3', 'other')", name='ck_auth_profiles_provider'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_profile_id')
    )
    op.create_index('ix_auth_profiles_enabled', 'auth_profiles', ['enabled'], unique=False)
    op.create_index('ix_auth_profiles_provider', 'auth_profiles', ['provider'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visual_line', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_brands_enabled', 'brands', ['enabled'], unique=False)
    op.create_table('job_asset_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'prepared'"), nullable=False),
    sa.Column('output_dir', sa.String(length=1200), nullable=False),
    sa.Column('manifest_path', sa.String(length=1200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('prepared', 'failed', 'cleaned')", name='ck_job_asset_bundles_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('niches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_products_brand_id_slug')
    )
    op.create_index('ix_products_brand_id', 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_enabled', 'products', ['enabled'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('auth_profile_id', sa.Integer(), nullable=True),
    sa.Column('rclone_remote', sa.String(length=255), nullable=True),
    sa.Column('root_path', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider in ('google_drive', 'local', 's3', 'other')", name='ck_sources_provider'),
    sa.ForeignKeyConstraint(['auth_profile_id'], ['auth_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index('ix_sources_enabled', 'sources', ['enabled'], unique=False)
    op.create_index('ix_sources_provider', 'sources', ['provider'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_uid', sa.String(length=160), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('rclone_remote', sa.String(length=255), nullable=True),
    sa.Column('remote_path', sa.String(length=1200), nullable=False),
    sa.Column('source_path', sa.String(length=1200), nullable=True),
    sa.Column('drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_ext', sa.String(length=40), nullable=True),
    sa.Column('mime_type', sa.String(length=180), nullable=True),
    sa.Column('type', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=160), nullable=True),
    sa.Column('people', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('best_for', sa.Text(), nullable=True),
    sa.Column('avoid_for', sa.Text(), nullable=True),
    sa.Column('orientation', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=160), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flip_horizontal_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('flip_vertical_allowed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('crop_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('zoom_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('speed_change_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reverse_allowed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('color_grade_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('has_visible_text', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('visible_text', sa.Text(), nullable=True),
    sa.Column('text_language', sa.String(length=40), nullable=True),
    sa.Column('has_logo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_watermark', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_faces', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_hands', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_product', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_directional_motion', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('safe_for_subtitles', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('safe_for_text_overlay', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('overlay_safe_area', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('shot_type', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('camera_motion', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('subject_position', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('visual_energy', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('pacing', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('best_scene_role', sa.String(length=40), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('loopable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('similarity_group', sa.String(length=160), nullable=True),
    sa.Column('reuse_cooldown_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("best_scene_role in ('hook', 'intro', 'explanation', 'emotional_peak', 'transition', 'broll', 'outro', 'background', 'unknown')", name='ck_assets_best_scene_role'),
    sa.CheckConstraint("camera_motion in ('static', 'handheld', 'pan', 'tilt', 'zoom', 'tracking', 'drone', 'unknown')", name='ck_assets_camera_motion'),
    sa.CheckConstraint("orientation in ('9:16', '16:9', 'square', 'unknown')", name='ck_assets_orientation'),
    sa.CheckConstraint("overlay_safe_area in ('top', 'center', 'bottom', 'left', 'right', 'full', 'unknown')", name='ck_assets_overlay_safe_area'),
    sa.CheckConstraint("pacing in ('slow', 'medium', 'fast', 'unknown')", name='ck_assets_pacing'),
    sa.CheckConstraint("provider in ('google_drive', 'local', 's3', 'other')", name='ck_assets_provider'),
    sa.CheckConstraint("shot_type in ('closeup', 'medium', 'wide', 'detail', 'establishing', 'unknown')", name='ck_assets_shot_type'),
    sa.CheckConstraint("status in ('active', 'inactive', 'missing', 'archived')", name='ck_assets_status'),
    sa.CheckConstraint("subject_position in ('center', 'left', 'right', 'top', 'bottom', 'full_frame', 'unknown')", name='ck_assets_subject_position'),
    sa.CheckConstraint("type in ('video', 'image', 'audio', 'unknown')", name='ck_assets_type'),
    sa.CheckConstraint("visual_energy in ('low', 'medium', 'high', 'unknown')", name='ck_assets_visual_energy'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_uid'),
    sa.UniqueConstraint('source_id', 'remote_path', name='uq_assets_source_id_remote_path')
    )
    op.create_index('ix_assets_brand_id', 'assets', ['brand_id'], unique=False)
    op.create_index('ix_assets_filename', 'assets', ['filename'], unique=False)
    op.create_index('ix_assets_last_used_at', 'assets', ['last_used_at'], unique=False)
    op.create_index('ix_assets_orientation', 'assets', ['orientation'], unique=False)
    op.create_index('ix_assets_product_id', 'assets', ['product_id'], unique=False)
    op.create_index('ix_assets_source_id_remote_path', 'assets', ['source_id', 'remote_path'], unique=False)
    op.create_index('ix_assets_status', 'assets', ['status'], unique=False)
    op.create_index('ix_assets_type', 'assets', ['type'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_collections_brand_id', 'collections', ['brand_id'], unique=False)
    op.create_index('ix_collections_product_id', 'collections', ['product_id'], unique=False)
    op.create_table('asset_collections',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'collection_id')
    )
    op.create_table('asset_niches',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'niche_id')
    )
    op.create_table('asset_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'tag', name='uq_asset_tags_asset_id_tag')
    )
    op.create_index('ix_asset_tags_asset_id', 'asset_tags', ['asset_id'], unique=False)
    op.create_index('ix_asset_tags_tag', 'asset_tags', ['tag'], unique=False)
    op.create_table('asset_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=160), nullable=False),
    sa.Column('renderer', sa.String(length=160), nullable=True),
    sa.Column('local_path', sa.String(length=1200), nullable=True),
    sa.Column('manifest_path', sa.String(length=1200), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_usages_asset_id', 'asset_usages', ['asset_id'], unique=False)
    op.create_index('ix_asset_usages_job_id', 'asset_usages', ['job_id'], unique=False)
    op.create_index('ix_asset_usages_used_at', 'asset_usages', ['used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_usages_used_at', table_name='asset_usages')
    op.drop_index('ix_asset_usages_job_id', table_name='asset_usages')
    op.drop_index('ix_asset_usages_asset_id', table_name='asset_usages')
    op.drop_table('asset_usages')
    op.drop_index('ix_asset_tags_tag', table_name='asset_tags')
    op.drop_index('ix_asset_tags_asset_id', table_name='asset_tags')
    op.drop_table('asset_tags')
    op.drop_table('asset_niches')
    op.drop_table('asset_collections')
    op.drop_index('ix_collections_product_id', table_name='collections')
    op.drop_index('ix_collections_brand_id', table_name='collections')
    op.drop_table('collections')
    op.drop_index('ix_assets_type', table_name='assets')
    op.drop_index('ix_assets_status', table_name='assets')
    op.drop_index('ix_assets_source_id_remote_path', table_name='assets')
    op.drop_index('ix_assets_product_id', table_name='assets')
    op.drop_index('ix_assets_orientation', table_name='assets')
    op.drop_index('ix_assets_last_used_at', table_name='assets')
    op.drop_index('ix_assets_filename', table_name='assets')
    op.drop_index('ix_assets_brand_id', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_sources_provider', table_name='sources')
    op.drop_index('ix_sources_enabled', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_products_enabled', table_name='products')
    op.drop_index('ix_products_brand_id', table_name='products')
    op.drop_table('products')
    op.drop_table('niches')
    op.drop_table('job_asset_bundles')
    op.drop_index('ix_brands_enabled', table_name='brands')
    op.drop_table('brands')
    op.drop_index('ix_auth_profiles_provider', table_name='auth_profiles')
    op.drop_index('ix_auth_profiles_enabled', table_name='auth_profiles')
    op.drop_table('auth_profiles')
    # ### end Alembic commands ###
